#pragma config(Motor,  port1,           R1Wheel,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           L1Wheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           R2Wheel,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           L2Wheel,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//variables
int wheelSpeed;
int joyThresh;
int wheelThresh;
int waitTime;
int wheelEncoderSpeed = abs(sensor[wheelEncoder]) // <-- SUDO CODE, replace with actual name of encoder
int encoderTimer = time1[T1];
int dataPointOne
int dataPointTwo

//this function sets all the wheel motors to the wheelSpeed
void setWheelSpeed() {
		motor[L1Wheel] = wheelSpeed;
		motor[L2Wheel] = wheelSpeed;
		motor[R1Wheel] = wheelSpeed;
		motor[R2Wheel] = wheelSpeed;
}

//this sets all the wheel motors to zero
void resetMotors() {
    wheelSpeed = 0;
    setWheelSpeed();
}

void bangBang() {
    waitTime = 30;
    while (1 == 1) {
        dataPointOne = wheelEncoderSpeed;
        wait1Msec(waitTime)
        dataPointTwo = wheelEncoderSpeed;
        // SUDO
        if ((dataPointTwo - dataPointOne)/waitTime) < minSpeed {
            wheelSpeed = (wheelSpeed + 27);
            setWheelSpeed();
            wait1Msec(waitTime)
        }
    }
}

//this function lets buttons control the wheel speed
void runTestWheelSpeed() {
	while (1 == 1) {

        // full speed
        while (vexRT[Btn8U] == 1) {
            wheelSpeed = 127;
            setWheelSpeed();
        }

    resetMotors();

        // half speed
        while (vexRT[Btn8D] == 1) {
            wheelSpeed = 60;
            setWheelSpeed();
        }

	resetMotors();

        // 3/4 speed
        while (vexRT[Btn8R] == 1) {
            wheelSpeed = 100;
            setWheelSpeed();
            bangBang();
        }

    resetMotors();

        // 1/4 speed
        while (vexRT[Btn8L] == 1) {
            wheelSpeed = 30;
            setWheelSpeed();
        }

    resetMotors();

    } // end of main while loop
} // end of function


task main() {

    runTestWheelSpeed();

} //ending bracket
