#pragma config(Motor,  port1,           R1Wheel,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           L1Wheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           R2Wheel,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           L2Wheel,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//variables
int wheelValue;

//this function sets all the wheel motors to one value
void setWheelValue() {
		motor[L1Wheel] = wheelValue;
		motor[L2Wheel] = wheelValue;
		motor[R1Wheel] = wheelValue;
		motor[R2Wheel] = wheelValue;
}

//this sets all the wheel motors to zero
void resetMotors() {
    wheelValue = 0;
    setWheelValue();
}

//this function lets buttons control the wheel speed
void runWheelButtons() {
	while (1 == 1) {

        // full speed
        while (vexRT[Btn8U] == 1) {
            wheelValue = 127;
            setWheelValue();
        }

    resetMotors();

        // half speed
        while (vexRT[Btn8D] == 1) {
            wheelValue = 60;
            setWheelValue();
        }

	resetMotors();

        // 3/4 speed
        while (vexRT[Btn8R] == 1) {
            wheelValue = 100;
            setWheelValue();
        }

    resetMotors();

        // 1/4 speed
        while (vexRT[Btn8L] == 1) {
            wheelValue = 30;
            setWheelValue();
        }

    resetMotors();

    } // end of main while loop
} // end of function



task main() {

    runWheelButtons();

} //ending bracket
