#pragma config(Motor,  port1,           R1Wheel,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           L1Wheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           R2Wheel,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           L2Wheel,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void resetMotors() {
		motor[L1Wheel] = 0;
		motor[L2Wheel] = 0;
		motor[R1Wheel] = 0;
		motor[R2Wheel] = 0;
}


void runWheelButtons() {
	while (1 == 1) {

	// full speed
	while (vexRT[Btn8U] == 1) {
		motor[L1Wheel] = 127;
		motor[L2Wheel] = 127;
		motor[R1Wheel] = 127;
		motor[R2Wheel] = 127;
		}

	resetMotors();

	// half speed
	while (vexRT[Btn8D] == 1) {
		motor[L1Wheel] = 60;
		motor[L2Wheel] = 60;
		motor[R1Wheel] = 60;
		motor[R2Wheel] = 60;
		}

	resetMotors();

	// 3/4 speed
	while (vexRT[Btn8R] == 1) {
		motor[L1Wheel] = 100;
		motor[L2Wheel] = 100;
		motor[R1Wheel] = 100;
		motor[R2Wheel] = 100;
		}

	resetMotors();

	// 1/4 speed
	while (vexRT[Btn8L] == 1) {
		motor[L1Wheel] = 30;
		motor[L2Wheel] = 30;
		motor[R1Wheel] = 30;
		motor[R2Wheel] = 30;
		}

	resetMotors();
} // end of while loop
} // end of function

task main()
{

runWheelButtons();

} //ending bracket
